CREATE TABLE agent_training_sessions (
 id VARCHAR(32) NOT NULL,
 tenant_id VARCHAR(128) NOT NULL,
 agent_id VARCHAR(32) NOT NULL,
 admin_user_id VARCHAR(128) NOT NULL,
 conversation_id VARCHAR(32) COLLATE utf8mb4_unicode_ci NOT NULL,
 base_version_id VARCHAR(32) NOT NULL,
 candidate_head VARCHAR(64) NOT NULL,
 candidate_config_json JSON NOT NULL,
 candidate_partial BOOLEAN NOT NULL DEFAULT FALSE,
 status VARCHAR(16) NOT NULL,
 row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 expires_at DATETIME(6) NOT NULL,
 validation_json JSON NULL,
 operation_json JSON NOT NULL,
 result_version_id VARCHAR(32) NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 active_slot TINYINT GENERATED ALWAYS AS (CASE WHEN status IN ('active','validating','ready') THEN 1 ELSE NULL END) STORED,
 PRIMARY KEY(id),
 UNIQUE KEY uq_training_scope(tenant_id,agent_id,id),
 UNIQUE KEY uq_training_active(tenant_id,agent_id,active_slot),
 UNIQUE KEY uq_training_conversation(conversation_id),
 KEY ix_training_owner(tenant_id,admin_user_id,id),
 CONSTRAINT ck_training_status CHECK(status IN ('active','validating','ready','published','cancelled','stale','expired')),
 CONSTRAINT ck_training_expiry CHECK(expires_at > created_at),
 CONSTRAINT ck_training_publication CHECK((status = 'published' AND result_version_id IS NOT NULL) OR (status <> 'published' AND result_version_id IS NULL)),
 CONSTRAINT fk_training_agent FOREIGN KEY(tenant_id,agent_id) REFERENCES agents(tenant_id,id),
 CONSTRAINT fk_training_base FOREIGN KEY(tenant_id,agent_id,base_version_id) REFERENCES agent_versions(tenant_id,agent_id,id),
 CONSTRAINT fk_training_result FOREIGN KEY(tenant_id,agent_id,result_version_id) REFERENCES agent_versions(tenant_id,agent_id,id),
 CONSTRAINT fk_training_conversation FOREIGN KEY(tenant_id,agent_id,conversation_id) REFERENCES agent_conversations(tenant_id,agent_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
ALTER TABLE agents ADD CONSTRAINT fk_agents_active_training FOREIGN KEY(tenant_id,id,active_training_session_id) REFERENCES agent_training_sessions(tenant_id,agent_id,id);
ALTER TABLE agent_versions ADD CONSTRAINT fk_versions_training FOREIGN KEY(tenant_id,agent_id,source_training_session_id) REFERENCES agent_training_sessions(tenant_id,agent_id,id);
